version: '3.5'
services:
  ldap_zimbra:
    build: .
    container_name: zimbra
    hostname: zimbra.example.com
    tty: true
    privileged: true
    ports:
      - '80:80'
      - '10389:389'
      - '7071:7071'